[build-system]
requires = ["setuptools", "wheel", "Cython", "oldest-supported-numpy", "scipy>=1.6", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.setuptools_scm]
